  services:
    backend:
      image: ghcr.io/pontolocal/backend
      container_name: pontolocal_backend
      ports:
        - "${BACKEND_PORT:-8080}:${BACKEND_PORT:-8080}"
      environment:
        BACKEND_PORT: ${BACKEND_PORT:-8080}
        DATABASE_USERNAME: ${DATABASE_USERNAME:-admin}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD:-admin}
        DATABASE_NAME: ${DATABASE_NAME:-pontolocal}
        DATABASE_HOST: ${DATABASE_HOST:-database}
        DATABASE_PORT: ${DATABASE_PORT:-5432}
        
    database:
      image: postgres:16
      container_name: pontolocal_database
      restart: always
      ports:
        - "${DATABASE_PORT:-5432}:5432"
      environment:
          POSTGRES_USER: ${DATABASE_USERNAME:-admin}
          POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-admin}
          POSTGRES_DB: ${DATABASE_NAME:-ponto_local}
      volumes:
        - postgres_data:/var/lib/postgresql/data
    
    pgadmin:
      image: dpage/pgadmin4
      container_name: pontolocal_pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      ports:
        - "${PGADMIN_PORT:-5000}:80"

      volumes:
        - pgadmin_data:/var/lib/pgadmin

  volumes:
    postgres_data:
    pgadmin_data:
